spring:
  application:
    name: gateway-zuul # 指定应用名称

# docker-compose swarm
  cloud:
    inetutils:
      preferred-networks:
      - 10.0   # 设置注册到Eureka中心的优选服务地址

server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-eureka:8761/eureka/
  instance:
    #心跳时间，服务续约间隔时间 （默认30秒）
    lease-renewal-interval-in-seconds: 2
    #发呆时间，服务续约到期时间（缺省90秒）
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}


#设置Hystrix熔断器判定超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
zuul:
  ignoredServices: '*'
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
    order-service:
       path: /order-service/**
       serviceId: order-service
