#DB Configuration
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://host.docker.internal:3306/microservice_mallmanagement?useSSL=false
#    与Docker整合时可使用以下配置（也可以使用具体的ip+端口）
    url: jdbc:mysql://mysql:30001/microservice_mallmanagement?useSSL=false
    username: root
    password: root
  application:
      name: order-service # 指定应用名称

# docker-compose swarm
  cloud:
    inetutils:
      preferred-networks:
      - 10.0   # 设置注册到Eureka中心的优选服务地址

server:
  port: 7900 # 指定该Eureka实例的端口号
eureka:
  instance:
        prefer-ip-address: true  # true - 优选通过IP地址找到对应的服务名称
        instance-id: ${spring.application.name}:${spring.application.instance_id}:${random.value}
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/  #配置eureka注册中心地址
#      上线测试需要使用以下配置
      defaultZone: http://eureka-server:30002/eureka/

