#DB Configuration
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://host.docker.internal:3306/microservice_mallmanagement?useSSL=false
#    与Docker整合时可使用以下配置（也可以使用具体的ip+端口）
    url: jdbc:mysql://mysql-mysql:3306/microservice_mallmanagement?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
  application:
      name: order-service # 指定应用名称

# docker-compose swarm
  cloud:
    inetutils:
      preferred-networks:
      - 10.0   # 设置注册到Eureka中心的优选服务地址

server:
  port: 7900 # 指定该Eureka实例的端口号
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-eureka:8761/eureka/
  instance:
    #心跳时间，服务续约间隔时间 （默认30秒）
    lease-renewal-interval-in-seconds: 2
    #发呆时间，服务续约到期时间（缺省90秒）
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html


